from .io import (
    build_deck_output_path,
    build_log_output_path,
    build_outline_output_path,
    build_ppt_output_path,
    default_deck_output_path,
    default_log_output_path,
    default_outline_output_path,
    default_ppt_output_path,
    load_deck_document,
    load_outline_document,
    write_deck_document,
    write_outline_document,
)
from .ppt_engine import RenderArtifacts, generate_ppt
from .schema import (
    DeckDocument,
    OutlineDocument,
    OutlineItem,
    SUPPORTED_LAYOUTS,
    SUPPORTED_THEMES,
    ThemeMeta,
    ValidatedDeck,
    collect_deck_warnings,
    normalize_deck_payload,
    validate_deck_payload,
)
from .services import (
    DeckGenerationRequest,
    OutlineGenerationRequest,
    V2MakeArtifacts,
    generate_deck_with_ai,
    generate_outline_with_ai,
    make_v2_ppt,
)
from .theme_loader import ThemeSpec, available_theme_names, load_theme

__all__ = [
    "DeckDocument",
    "DeckGenerationRequest",
    "OutlineDocument",
    "OutlineGenerationRequest",
    "OutlineItem",
    "RenderArtifacts",
    "SUPPORTED_LAYOUTS",
    "SUPPORTED_THEMES",
    "ThemeMeta",
    "ThemeSpec",
    "V2MakeArtifacts",
    "ValidatedDeck",
    "available_theme_names",
    "build_deck_output_path",
    "build_log_output_path",
    "build_outline_output_path",
    "build_ppt_output_path",
    "collect_deck_warnings",
    "default_deck_output_path",
    "default_log_output_path",
    "default_outline_output_path",
    "default_ppt_output_path",
    "generate_deck_with_ai",
    "generate_outline_with_ai",
    "generate_ppt",
    "load_deck_document",
    "load_outline_document",
    "load_theme",
    "make_v2_ppt",
    "normalize_deck_payload",
    "validate_deck_payload",
    "write_deck_document",
    "write_outline_document",
]
